version: "3.9"
services:
  chanchito:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000" # puerto de la app
      # si quieres mas puertos, solo agrega mas lineas
    links:
      - monguito # nombre del contenedor a mappear
    volumes:
      - .:/home/app
  monguito:
    image: mongo
    ports:
      - "27017:27017" # puerto de mongo, el de la izquierda es el anfitrion, el de la derecha es el contenedor
    environment:
      - MONGO_INITDB_ROOT_USERNAME=luiggy
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db # de donde sacar los datos para guardarlos en el host y recuperarlos en caso de que se borre el contenedor

volumes:
  mongo-data: # guarda los datos de manera local